### ISSUE TITLE
Malformed source in manifest

### ISSUE THREAD

**Issue by wjt** [flathub/com.github.unrud.RemoteTouchpad#3]
The manifest currently defines the following source:

https://github.com/flathub/com.github.unrud.RemoteTouchpad/blob/cc7416712a2206f41aadeca1d5a4dc3b6e521036/com.github.unrud.RemoteTouchpad.yaml#L42-L50

Notice that the "url", "tag", "commit" and "dest" keys are all specified twice. I think this is meant to be two different sources.

I spotted this while trying to parse the manifest with [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker/).

**Comment by Unrud** [comment]
> I think this is meant to be two different sources.

Yes. It didn't cause a problem because the first source is only required for tests.

Fixed in 2408f0ff548ce55920c6137e24f1b0dc5e4bb7e0

Thank you.
